sudo: required
dist: trusty
language: node_js
git:
  depth: 10
node_js:
  - "4"
  - "6"
before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install 2.2
  - rvm use 2.2 --fuzzy
  - npm install -g npm@3
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export BOOTSBLOGGER_DO_VALIDATOR=$?; true
install:
  - bundle install --deployment --jobs=3
  - npm install
cache:
  directories:
    - node_modules
    - vendor/bundle
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
  matrix:
    - BOOTSBLOGGER_TEST=core
    - BOOTSBLOGGER_TEST=validate-html-docs
matrix:
  fast_finish: true
  exclude:
    - node_js: "4"
      env: BOOTSBLOGGER_TEST=validate-html-docs
